home/urls.py
from django.urls import path
from home.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
]

ngoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('pages/', include('pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Slider(models.Model):
    subtitle = models.CharField(max_length=255, verbose_name='Sub Title',blank=True, null=True)
    title = models.CharField(max_length=255, verbose_name='Title',null=True)
    description = models.TextField(verbose_name='Description',blank=True, null=True)
    image = models.ImageField(upload_to='slider/', verbose_name='Image', help_text='Image size should be 1520x570 px')
    link = models.CharField(max_length=255, verbose_name='Link', blank=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name='Is Active', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class About(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    description = models.TextField(verbose_name='Description')
    image = models.ImageField(upload_to='about/', verbose_name='Image')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'History'
        
class MessageFromDirector(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    description = RichTextField(null=True)
    image = models.ImageField(upload_to='about/', verbose_name='Image')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Message From Director'
        
class KeyAchievement(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    description = RichTextField()
    image = models.ImageField(upload_to='about/', verbose_name='Image')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Key and Achievement'
        
class Mission(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    description = RichTextField()
    image = models.ImageField(upload_to='about/', verbose_name='Image')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Vision, Mission & Strategy'
        
class Outcome(models.Model):
    description = RichTextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.description
    
class Course(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    image = models.ImageField(upload_to='course/', verbose_name='Image')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class ThreeZero(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    image = models.ImageField(upload_to='popular_course/', verbose_name='Image')
    description = RichTextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Three Zeros'
    
class Facility(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    description = RichTextField(null=True)
    image = models.ImageField(upload_to='facility/', verbose_name='Image')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
PROGRAM_STATUS = (
    ('completed', 'Completed'),
    ('ongoing', 'On Going'),
)
    
class Program(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    summary = models.TextField(verbose_name='Summary')
    description = RichTextField(null=True)
    image = models.ImageField(upload_to='program/', verbose_name='Image')
    status = models.CharField(max_length=50, choices = PROGRAM_STATUS, verbose_name='Status')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class News(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title', unique=True)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    description = RichTextField()
    image = models.ImageField(upload_to='blog/', verbose_name='Image')
    location = models.CharField(max_length=255, verbose_name='Location')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "News"
        
class Article(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title', unique=True)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    description = RichTextField()
    image = models.ImageField(upload_to='blog/', verbose_name='Image')
    location = models.CharField(max_length=255, verbose_name='Location')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Article"
    
class Events(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title', unique=True)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    description = RichTextField()
    image = models.ImageField(upload_to='title/', verbose_name='Image')
    location = models.CharField(max_length=255, verbose_name='Location')
    event_date = models.CharField(max_length=255,null=True, verbose_name='Event Date')
    event_time = models.CharField(max_length=255,null=True, verbose_name='Event Time')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Events'
    
class Testomonials(models.Model):
    fullname = models.CharField(max_length=255, verbose_name='Full Name')
    designation = models.CharField(max_length=255, verbose_name='Designation')
    image = models.ImageField(upload_to='testomonials/', verbose_name='Image')
    description = RichTextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fullname
    
    class Meta:
        verbose_name_plural = 'Testomonials'
        
class ImageCategory(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title', unique=True)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    image = models.ImageField(upload_to='image_category/', verbose_name='Image', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class ImageGallery(models.Model):
    category = models.ForeignKey(ImageCategory, on_delete=models.CASCADE, verbose_name='Image Category')
    image = models.ImageField(upload_to='image_gallery/', verbose_name='Image')
    
    def __str__(self):
        return self.category.title
    
class Video(models.Model):
    link = models.URLField(max_length=200)
    
    def __str__(self):
        return self.link
    
class Archive(models.Model):
    title = models.CharField(max_length=255, verbose_name='Title')
    files = models.FileField(upload_to='archive/', verbose_name='Files')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class OurPartnerDatas(models.Model):
    title = models.CharField(max_length=255, verbose_name='Name')
    tagline = models.CharField(max_length=255, verbose_name='Tag Line')
    description = RichTextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
     
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Our Partner Description'
    
class OurPartner(models.Model):
    name = models.CharField(max_length=255, verbose_name='Name')
    image = models.ImageField(upload_to='our_partner/', verbose_name='Image')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
     
    def __str__(self):
        return self.name
    
class AnnualReport(models.Model):
    title = models.CharField(max_length=255)
    image = models.FileField(upload_to='annualreport_images/', max_length=100, null=True,blank=True)
    files = models.FileField(upload_to='annualreport/', max_length=200)
    
    def __str__(self):
        return self.title
    
POSITION = (
    ('team', 'Team Member'),
    ('board', 'Board Member'),
    ('both', 'Both'),
)
    
class Team(models.Model):

templates/frontend/pages/archives.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
<!-- page-banner-start -->
<div class="page-banner" style="background-image: url({% static 'frontend/images/img/page-banner.jpeg' %})">
  <div class="enquiry">
    <a href="{% url 'contact' %}">
      <button>Enquiry</button>
    </a>
  </div>
  <a href="mailto:info@nlrnepal.org.np">
  <div class="side-email">
    <div class="icon">
      <img src="{% static 'frontend/images/icons/mail.svg' %}" alt="" />
    </div>
    <span> info@nlrnepal.org.np </span>
  </div>
  </a>

  <a href="tel:+977-014784296">
  <div class="side-call">
    <div class="icon">
      <img src="{% static 'frontend/images/icons/phone.svg' %}" alt="" />
    </div>
    <span>+977-014784296</span>
  </div>
  </a>
  <div class="page-title">
    <h1>About</h1>
    <h6>
      <a href="/"> Home</a>
      <i class="fas fa-chevron-right"></i> History
    </h6>
  </div>
</div>
<!-- page-banner-end -->

<!-- download-start -->
<section>
    <div class="wrapper">
        <div class="download">
            <div class="list">
                {% for item in reports %}
                <div>
                    <div class="item">
                        {% if item.image %}
                        <div class="image">
                            <div class="img" style="background-image: url({{item.image.url}})"></div>
                        </div>
                        {% else %}
                        <div class="image">
                            <div class="img" style="background-image: url({% static 'frontend/images/Report.png' %})"></div>
                        </div>
                        {% endif %}
                        <div class="details">
                            <h3 class="name">{{item.title}}</h3>
                        </div>
                        <a href="{{item.files.url}}" download="{{item.files.url}}">
                            <button>Download</button>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="btn">
                <button class="load-more-btn">Load More</button>
              </div>
        </div>
    </div>
</section>
<!-- download-end -->

<script>
    const productComment = document.querySelector(".download");

    if (productComment) {
      const comments = document.querySelectorAll(".download .item");
      const loadMoreBtn = document.querySelector(".download .load-more-btn");
      let noOfItems = 8;

      const loadComment = () => {
        comments.forEach((comment, idx) => {
          if (idx < noOfItems) {
            comment.classList.add("active");
          } else {
            comment.classList.remove("active");
          }
        });
      };
      loadComment();

      loadMoreBtn.addEventListener("click", () => {
        loadComment();

        if (comments.length <= noOfItems) {
          loadMoreBtn.innerHTML = "Load Less";
          noOfItems = 8;
        } else {
          loadMoreBtn.innerHTML = "Load More";
          noOfItems += 1;
        }
      });
    }
  </script>

{% endblock content %}

templates/frontend/pages/article-details.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
<div class="all-details-page">
    <div class="wrapper">
      <div class="blog-post">
        <div class="image">
          <div class="img" style="background-image: url({{article.image.url}})"></div>
        </div>
        <div class="details">
          <div class="name">
            {{article.title}}
          </div>
          <p class="desc">
            {{article.description|safe}}
          </p>
        </div>
      </div>

      <div class="recent-post">
        <div class="title">Recent Post</div>
        <div class="list">
        {% for item in recent_articles %}
          <div class="item">
            <div class="recent-image">
              <div class="img" style="background-image: url({{item.image.url}})"></div>
            </div>
            <div class="name">
              <a href="{% url 'articledetail' item.slug %}">
                {{item.title|truncatewords:6}}
              </a>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/frontend/pages/articles.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
  <!-- page-banner-start -->
  <div class="page-banner" style="background-image: url({% static 'frontend/images/img/page-banner.jpeg' %})">
    <div class="enquiry">
      <a href="{% url 'contact' %}">
        <button>Enquiry</button>
      </a>
    </div>
    <a href="mailto:info@nlrnepal.org.np">
    <div class="side-email">
      <div class="icon">
        <img src="{% static 'frontend/images/icons/mail.svg' %}" alt="" />
      </div>
      <span> info@nlrnepal.org.np </span>
    </div>
    </a>

    <a href="tel:+977-014784296">
    <div class="side-call">
      <div class="icon">
        <img src="{% static 'frontend/images/icons/phone.svg' %}" alt="" />
      </div>
      <span>+977-014784296</span>
    </div>
    </a>
    <div class="page-title">
      <h1>About</h1>
      <h6>
        <a href="/"> Home</a>
        <i class="fas fa-chevron-right"></i> History
      </h6>
    </div>
  </div>
  <!-- page-banner-end -->

  <!-- blog-start -->
  <section>
    <div class="wrapper">
      <div class="blog">
        <div class="title">
          <h4>Article</h4>
          <h2>Recent Articles</h2>
        </div>

        <div class="list">
        {% for article in articles %}
        <div>

          <div class="item">
            <a href="{% url 'articledetail' article.slug %}">
              <div class="image">
                <div class="img" style="background-image: url({{article.image.url}})"></div>
              </div>
            </a>
            <div class="details">
              <h6>{{article.created_at}}</h6>
              <a href="{% url 'articledetail' article.slug %}">
                <h4 class="name">{{article.title|truncatewords:8}}</h4>
              </a>
              <p>
                {{article.content|truncatewords:10}}
              </p>
              <a href="{% url 'articledetail' article.slug %}">
                <button>View</button>
              </a>
            </div>
          </div>
        </div>

          {% endfor %}
        </div>
      </div>
    </div>
  </section>
  <!-- blog-end -->
{% endblock content %}

templates/frontend/pages/board-member.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
  <!-- page-banner-start -->
  <div class="page-banner" style="background-image: url({% static 'frontend/images/img/page-banner.jpeg' %})">
    <div class="enquiry">
      <a href="{% url 'contact' %}">
        <button>Enquiry</button>
      </a>
    </div>
    <a href="mailto:info@nlrnepal.org.np">
    <div class="side-email">
      <div class="icon">
        <img src="{% static 'frontend/images/icons/mail.svg' %}" alt="" />
      </div>
      <span> info@nlrnepal.org.np </span>
    </div>
    </a>

    <a href="tel:+977-014784296">
    <div class="side-call">
      <div class="icon">
        <img src="{% static 'frontend/images/icons/phone.svg' %}" alt="" />
      </div>
      <span>+977-014784296</span>
    </div>
    </a>
    <div class="page-title">
      <h1>About</h1>
      <h6>
        <a href="/"> Home</a>
        <i class="fas fa-chevron-right"></i> History
      </h6>
    </div>
  </div>
  <!-- page-banner-end -->

    <!-- teams-start -->
    <section class="bg">
      <div class="wrapper">
        <div class="teams">
          <div class="title">
            <h4>Board</h4>
            <h2>Board Member</h2>
          </div>
          <div class="list list-grid">
            {% for item in teams %}
            <div class="item">
              <div class="image">
                <div class="img" style="background-image: url({{item.image.url}})"></div>
              </div>
              <div class="details">
                <div class="name">{{item.fullname}}</div>
                <div class="info">{{item.designation}}</div>
                
                <div class="icons">
                  {% if item.facebook %}
                  <a href="{{item.facebook}}" target="_blank">
                    <div class="icon">
                      <i class="fab fa-facebook-f"></i>
                    </div>
                  </a>
                  {% endif %}
                  {% if item.linkedin %}
                  <a href="{{item.linkedin}}" target="_blank">
                    <div class="icon">
                      <i class="fab fa-linkedin"></i>
                    </div>
                  </a>
                  {% endif %}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </section>
    <!-- teams-end -->
  {% endblock content %}

templates/frontend/pages/completed-programs.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
<!-- page-banner-start -->
  <div class="page-banner" style="background-image: url({% static 'frontend/images/img/page-banner.jpeg' %})">
    <div class="enquiry">
      <a href="{% url 'contact' %}">
        <button>Enquiry</button>
      </a>
    </div>
    <a href="mailto:info@nlrnepal.org.np">
    <div class="side-email">
      <div class="icon">
        <img src="{% static 'frontend/images/icons/mail.svg' %}" alt="" />
      </div>
      <span> info@nlrnepal.org.np </span>
    </div>
    </a>

    <a href="tel:+977-014784296">
    <div class="side-call">
      <div class="icon">
        <img src="{% static 'frontend/images/icons/phone.svg' %}" alt="" />
      </div>
      <span>+977-014784296</span>
    </div>
    </a>
    <div class="page-title">
      <h1>About</h1>
      <h6>
        <a href="/"> Home</a>
        <i class="fas fa-chevron-right"></i> History
      </h6>
    </div>
  </div>
<!-- page-banner-end -->
<section>
    <div class="wrapper">
        <div class="blog">
            <div class="title">
                <h4>Programs</h4>
                <h2>Our Ongoing Programs</h2>
            </div>

            <div class="list">
                {% for program in programs  %}
                <div>
                    <a href="{% url 'programdetail' program.slug %}">
                        <div class="item">
                            <div class="image">
                                <div class="img" style="background-image: url({{program.image.url}})"></div>
                            </div>
                            <div class="details">
                                <h6>{{program.created_at}}</h6>
                                <a href="{% url 'programdetail' program.slug %}">
                                    <h4 class="name">{{program.title|truncatewords:3}}</h4>
                                </a>
                                <p>
                                    {{program.summary|safe|truncatewords:15}}
                                </p>
                                <a href="{% url 'programdetail' program.slug %}">
                                    <button>View</button>
                                </a>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/frontend/pages/gallery.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
  <!-- gallery-start -->
  <section class="wow animate__animated animate__bounceInUp">
    <div class="gallery grid-gallery">
      <div class="title">
        <h4>GALLERY</h4>
        <h2>NLR NGO Gallery</h2>
      </div>

      <ul class="switch-btn">
        <li class="active" data-filters="data-image">Images</li>
        <li data-filters="data-video">Videos</li>
      </ul>

      <div class="images-list galleryBox data-image">
        {% for item in imagecategory %}
        <div class="item">
          <div class="image" style="background-image: url( {{item.image.url}} )"></div>
          <div id="galleryBtn" class="name">{{item.title}}
          </div>
        </div>
        <div class="gallery-popup">
          <div class="gallery-bg"></div>
          <div class="close-gallery-btn">
            <img src="{% static 'frontend/images/icons/close_big_light.svg' %}" alt="" />
          </div>
          <div class="title">{{item.title}}</div>
          <div class="gallery-images">
            <div class="swiper-container mySwiper">
              <div class="swiper-wrapper">
                {% for i in item.imagegallery_set.all %}
                  <div class="swiper-slide" style="background-image: url({{i.image.url}})"></div>
                {% endfor %}
              </div>
              <div class="swiper-button-next"></div>
              <div class="swiper-button-prev"></div>
            </div>
          </div>
        </div>
        {% endfor %}
        <div class="images-list galleryBox data-video">
          <div class="item-video">
            {% for v in videos %}
            <video controls>
              <source
              src="{{v.link}}"
              />
            </video>
            {% endfor %}
          </div>
        </div>

      </div>
    </div>
  </section>
  <!-- gallery-end -->


  <script>
    // gallery-popup
    var swiper = new Swiper(".gallery-popup .mySwiper", {
      slidesPerView: 1,
      spaceBetween: 10,
      centeredSlides: true,
      autoplay: {
        delay: 3000,
        disableOnInteraction: false,
      },
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
      breakpoints: {
        640: {
          slidesPerView: 1,
          spaceBetween: 30,
        },
        768: {
          slidesPerView: 2,
          spaceBetween: 30,
        },
        1024: {
          slidesPerView: 3,
          spaceBetween: 30,
        },
      },
    });
  </script>

  <script>
    // gallery
    $(document).ready(function () {
      $(".galleryBox").not(".data-image").hide("1000");
    });

    $(document).ready(function () {
      $(".gallery ul li").click(function () {
        const value = $(this).attr("data-filters");
        $(".galleryBox")
          .not("." + value)
          .hide("1000");
        $(".galleryBox")
          .filter("." + value)
          .show("1000");
      });

      $(".gallery ul li").click(function () {
        $(this).addClass("active").siblings().removeClass("active");
      });
    });
  </script>

{% endblock content %}

templates/frontend/pages/message_from_director.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
  <!-- page-banner-start -->
  <div class="page-banner" style="background-image: url({% static 'frontend/images/img/page-banner.jpeg' %})">
    <div class="enquiry">
      <a href="{% url 'contact' %}">
        <button>Enquiry</button>
      </a>
    </div>
    <a href="mailto:info@nlrnepal.org.np">
    <div class="side-email">
      <div class="icon">
        <img src="{% static 'frontend/images/icons/mail.svg' %}" alt="" />
      </div>
      <span> info@nlrnepal.org.np </span>
    </div>
    </a>

    <a href="tel:+977-014784296">
    <div class="side-call">
      <div class="icon">
        <img src="{% static 'frontend/images/icons/phone.svg' %}" alt="" />
      </div>
      <span>+977-014784296</span>
    </div>
    </a>
    <div class="page-title">
      <h1>About</h1>
      <h6>
        <a href="/"> Home</a>
        <i class="fas fa-chevron-right"></i> History
      </h6>
    </div>
  </div>
  <!-- page-banner-end -->
  <br>
  <!-- about-page-start -->
  <div class="wrapper">
    
    {% for about in msg_from_dir|slice:1 %}
    <div class="about-page">
      <div class="image">
        <div class="img" style="background-image: url({{about.image.url}})"></div>
      </div>

      <div class="details">
        <div class="title">
          <h2>{{about.title}}</h2>
        </div>
       
        <p>
            {{about.description|safe}}
        </p>
      </div>



      <div class="details">
       
      </div>
    </div>
    {% endfor %}

  </div>
  <!-- about-page-end -->
{% endblock content %}

templates/frontend/pages/mission.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
<!-- about-page-start -->
<div class="page-banner" style="background-image: url({% static 'frontend/images/img/page-banner.jpeg' %})">
  <div class="enquiry">
    <a href="{% url 'contact' %}">
      <button>Enquiry</button>
    </a>
  </div>
  <a href="mailto:info@nlrnepal.org.np">
  <div class="side-email">
    <div class="icon">
      <img src="{% static 'frontend/images/icons/mail.svg' %}" alt="" />
    </div>
    <span> info@nlrnepal.org.np </span>
  </div>
  </a>

  <a href="tel:+977-014784296">
  <div class="side-call">
    <div class="icon">
      <img src="{% static 'frontend/images/icons/phone.svg' %}" alt="" />
    </div>
    <span>+977-014784296</span>
  </div>
  </a>
  <div class="page-title">
    <h1>About</h1>
    <h6>
      <a href="/"> Home</a>
      <i class="fas fa-chevron-right"></i> History
    </h6>
  </div>
</div>
<br>
<div class="wrapper">
    <div class="about-page">
        {% for m in mission %}
        <div class="image">
            <div class="img" style="background-image: url({{m.image.url}})"></div>
        </div>

        <div class="details">
          <h4>Vision</h4>
          <p>A world free of leprosy and exclusion due to disabilities</p>

          <h4>Our Mission</h4>
          <p>
            We promote and support health, ability and full inclusion in society
            for persons affected by leprosy or living with disabilities
          </p>

          <h4>Strategy</h4>
          <p>
            NLR works with governments, NGOs, research institutions and Disabled
            People’s Organizations.
          </p>

          <!-- <ul>
            <li>
              To provide learning environment where individuals are inspired and
              empowered to become responsible managers, entrepreneurs, leaders
              and researchers in different management fields.
            </li>
            <li>
              To enhance critical thinking and decision making skills of
              students through practical, research based and innovative academic
              programs.
            </li>
            <li>
              To promote entrepreneurship through innovation and contribute in
              nation’s development by creating employments.
            </li>
          </ul> -->
        </div>

        <div class="details">
            <div class="title">
                <h2>Vision, Mission & Strategy</h2>
                <h4>{{m.title}}</h4>
            </div>
            <p>
                    {{m.description|safe}}
            </p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

templates/frontend/pages/news-details.html
{% extends "frontend/base.html" %}
{% load static %}
{% block content %}
<div class="all-details-page">
    <div class="wrapper">
      <div class="blog-post">
        <div class="image">
          <div class="img" style="background-image: url({{news.image.url}})"></div>
        </div>
        <div class="details">
          <div class="name">
            {{news.title}}
          </div>
          <p class="desc">
            {{news.description|safe}}
          </p>
        </div>
      </div>

      <div class="recent-post">
        <div class="title">Recent Post</div>
        <div class="list">
        {% for item in recent_news %}
          <div class="item">
            <div class="recent-image">
              <div class="img" style="background-image: url({{item.image.url}})"></div>
            </div>
            <div class="name">
              <a href="{% url 'newsdetail' item.slug %}">
                {{item.title|truncatewords:6}}
              </a>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}